// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwdqfdjeyheudbdwssnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3ZHFmZGpleWhldWRiZHdzc253Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NzczODksImV4cCI6MjA1OTI1MzM4OX0.9h8zhRjOLahEAEKcMrrngFpu_Bx1ZCaDkjfGq4tA4V4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);